### ISSUE TITLE
META shows version 0.2.4

### ISSUE THREAD

**Issue by hcarty** [c-cube/gen#10]
It looks like at least some of the oasis-generated files are not synced up.  `src/META` lists the version number as 0.2.4, `_oasis` as 0.4.  I ran into this while trying to constrain the version for a local project.

**Comment by c-cube** [comment]
https://github.com/ocaml/opam-repository/pull/6442 should fix it, I hope.

**Comment by hcarty** [comment]
Thanks! I should be able to test tomorrow.

**Comment by hcarty** [comment]
Fixed!  Thank you very much for the quick fix.
