### ISSUE TITLE
Upstream BuckleScript support?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [c-cube/gen#16]
Hey! (I meant to catch you one more time this week at ReasonConf, but I had to ditch early.)

I maintain a [bs-gen](https://github.com/ELLIOTTCABLE/bs-gen#bs-gen) fork of your work; it's literally [just a few `.json` files](https://github.com/c-cube/gen/compare/master...ELLIOTTCABLE:master) added to the repository, and then [published to npm](https://www.npmjs.com/package/bs-gen).

Unfortunately, occasionally, I have to bump the version for npm- or BuckleScript-specific reasons — for instance, with the release last week of BuckleScript's support for 4.06, I've been going through my npm repackagings of opam packages and refreshing. Thing is, I don't want to decouple the version-number of `bs-gen` from your upstream release; it's *such* a simple repackaging …

Do you have any interest in letting me upstream those additions? I'm happy to keep carrying the maintenance burden of anything BuckleScript- or npm-specific. (And then bumping the opam version-number to `0.5.2`, so it can stay in sync with the npm version.)

**Comment by c-cube** [comment]
Hi!

No worries, it's a lot of people, etc. Nice to have met you nonetheless.

> Do you have any interest in letting me upstream those additions? I'm happy to keep carrying the maintenance burden of anything BuckleScript- or npm-specific. (And then bumping the opam version-number to `0.5.2`, so it can stay in sync with the npm version.)

That sounds good, I don't mind having a few more json files. A 0.5.2
would make sense anyway, master is ahead of last release. PR welcome!
